# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build 64 bit
      run: dotnet publish -o publish-arm64 -c Release --runtime linux-arm64 --self-contained /p:DebugType=None /p:DebugSymbols=false
    - name: Build 32 bit
      run: dotnet publish -o publish-arm32 -c Release --runtime linux-arm --self-contained /p:DebugType=None /p:DebugSymbols=false
    - name: Upload 64 bit
      uses: actions/upload-artifact@v4.3.0
      with: 
        name: ekisg-linux-arm64
        path: publish-arm64
    - name: Upload 32 bit
      uses: actions/upload-artifact@v4.3.0
      with: 
        name: ekisg-linux-arm32
        path: publish-arm32

    
    
